### ISSUE TITLE
cdflib version requirement an issue with PyHC Summer School HelioCloud setup

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatNASA#111]
**Is your feature request related to a problem? Please describe.**
Current version requirement is cdflib<0.3.20 which directly contradicts another PyHC package requirement, which, by memory, is cdflib>0.3.20.

**Describe the solution you'd like**
A more relaxed cdflib requirement.

**Describe alternatives you've considered**
Leaving pysatNASA out of demos, which would be a real bummer.

**Additional context**
Per brief discussion in developer meeting relaxing requirement may not be an issue.

**Comment by jklenzing** [comment]
The limit has been in place for a year, with multiple new versions of `cdflib` released.  Going to test against new version.

**Comment by jklenzing** [comment]
Can't find the rationale for the cap, but I remember that 3.20.0 did not work.  Using the latest creates errors in the omni hro instrument: https://github.com/pysat/pysatNASA/runs/6199105356?check_suite_focus=true

**Comment by jklenzing** [comment]
Update: it looks like 0.4.4 fixes the metadata issues documented in #95.

**Comment by jklenzing** [comment]
Note that versions below 0.4.4 do not fix this issue.  For consistency, we would need to have this as a minimum or maximum version.

**Comment by rstoneback** [comment]
Based upon your report 0.4.4 should be a minimum. It is also compatible with the other package using cdflib with a req of >= 0.4.3

**Comment by jklenzing** [comment]
0.4.3 doesn't work here.  We'd either have to set 0.4.4 as the minimum, or use a try-except for backwards compatibility

**Comment by jklenzing** [comment]
Closing with merge of #112
