### ISSUE TITLE
Add ACE data

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatNASA#127]
**Is your feature request related to a problem? Please describe.**
The Level 2 ACE data is most reliably accessible through CDAWeb, and so should be added here.  I'd like to show the difference between the L2 and L1 data available from pysatSpaceWeather, to highlight the dangers of using L1 data.

**Describe the solution you'd like**
At a minimum, the following L2 instruments added:
- [x] epam
- [x] mag
- [x] sis
- [x] swepam 
 
**Describe alternatives you've considered**
Adding them to the pysatSpaceWeather package, but that seems bad.

**Additional context**
This data source is ideal for testing the performance of the ACE to OMNI function available in pysatSpaceWeather.

**Comment by jklenzing** [comment]
https://cdaweb.gsfc.nasa.gov/pub/data/ace/

**Comment by jklenzing** [comment]
Would these be pandas or xarray datasets?  Thinking about workflow...

**Comment by aburrell** [comment]
I think they're pandas.

**Comment by jklenzing** [comment]
Running through some basic tests on this.  The first thing I've noticed is that we will have duplicate `ace_epam` modules, for instance, which will mess with the registry unless we force one to use a different name, such as `acel2_epam`.

**Comment by jklenzing** [comment]
Also, none of the files are loading in the default cdf routines

**Comment by aburrell** [comment]
> Running through some basic tests on this. The first thing I've noticed is that we will have duplicate ace_epam modules, for instance, which will mess with the registry unless we force one to use a different name, such as acel2_epam.

This is unfortunate :/ Your suggested solution is good enough, but not very elegant.  I guess there can be a standard where we set a primary repository for a platform/instrument combo and the other repositories add a qualifier to the platform?

**Comment by jklenzing** [comment]
> This is unfortunate :/ Your suggested solution is good enough, but not very elegant. I guess there can be a standard where we set a primary repository for a platform/instrument combo and the other repositories add a qualifier to the platform?

Probably needs an upgrade at the `pysat` level for that.  Another topic for tomorrow.  For a short-term fix, running directly from the module works, though the data directory will have a mix of pysatSpaceWeather and pysatNASA standards.  The tags / inst_ids are unique so far.

**Comment by jklenzing** [comment]
I've linked a branch with basic support (no documentation yet) as `enh/127`.  All instruments required xarray objects.  Could be good to test out the datasets while discussion continues.

**Comment by jklenzing** [comment]
Discussion from 10/19: add '-l2' to the names, eg, `ace_epam-l2`.

**Comment by jklenzing** [comment]
> Discussion from 10/19: add '-l2' to the names, eg, `ace_epam-l2`.

Dashes not allowed by python (cannot import).  Will have to use underscore.
