### ISSUE TITLE
BUG: Monthly file download

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatNASA#134]
**Describe the bug**
Currently, it looks like pysatNASA is getting the level 3a files from the 'CDF' directory on CDAWeb, but this means that a chunk of the data is missing.

**To Reproduce**
Compare: https://cdaweb.gsfc.nasa.gov/pub/data/timed/see/data/level3a_cdf/2008/11/

to

https://cdaweb.gsfc.nasa.gov/pub/data/timed/see/data/level3a/2008/

**Expected behavior**
There would not be data gaps based on the source

**Additional context**
This is likely a CDAWeb issue.

**Comment by jklenzing** [comment]
Linking to #14, #103.  TIMED SEE needs an overhaul anyway.

Looking at my local file structure, the cdf files are monthly versions of the daily netcdf files

**Comment by jklenzing** [comment]
Also linking to #104, since the netCDF support issues there apply here as well.

**Comment by aburrell** [comment]
Ok, so the real issue is that the download routine doesn't adjust the start date correctly for monthly data.  This is an issue with the download function that should be fixed, since a user should not be required to know the download file cadance.

**Comment by jklenzing** [comment]
Verified that this was fixed by #145.
