### ISSUE TITLE
BUG: ICON IVM inst_ids never active at the same time

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#152]
**Describe the bug**
The icon constellation object grabs both IVM objects, but neither exists at the same time.  Nominally, inst_id='a' is active, though inst_id='b' is active for campaigns.

**To Reproduce**
```
import datetime as dt
import pysat
import pysatNASA

icon = pysat.Constellation(const_module=pysatNASA.constellations.icon)
icon.download(dt.datetime(2020, 1, 1)
icon.load(2020, 1)
```

**Expected behavior**
Constellation should load.

**Additional context**
This is the result of a poor assumption.  Possible routes forward:
- Solve at `pysat` level to allow loading of instruments without data
- Include multiple instrument lists in the constellation object with a warning that loading by module is not recommended.
- Only keep 'a' in the default list

**Comment by aburrell** [comment]
One solution may be to have a merge/load function that creates an icon_ivm instrument from 'a' and 'b' combined.  Like combining multiple sources of F10.7, for example.

**Comment by jklenzing** [comment]
This is a pysat bug.  Fixed in https://github.com/pysat/pysat/pull/1101

Probably should add a note to the documentation so users know what to expect to close this here.

**Comment by jklenzing** [comment]
Added examples to the docstrings to show how to correctly load.
