### ISSUE TITLE
BUG: TIMED SABER and extra time variable

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#174]
**Describe the bug**
TIMED SABER is not correctly renaming the 'Epoch' variable to 'time'.  This breaks when the new concat routine for xarray in pysat 3.1.0 is used to load data.  This stems from SABER having a secondary time variable already.

**To Reproduce**
With pysat 3.1.0, run
```
import pysat

saber = pysat.Instrument('timed', 'saber')
saber.load(2019, 1)
```

**Expected behavior**
Data should load normally

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: all tested in Github Actions
 - Version python 3.9, 3.10, 3.11
 - pysat 3.1.0

**Additional context**
Since time already exists, Epoch does not get renamed.

https://github.com/pysat/pysatNASA/blob/71b807447c86bc1fb7e08dd3d06900c0a4863fed/pysatNASA/instruments/methods/cdaweb.py#L379-L382

**Comment by jklenzing** [comment]
Potentially could solve by adding `drop_vars` similar to `drop_dims` kwarg already used.  Or could rename this variable (also using new kwarg) so that data is preserved..

**Comment by aburrell** [comment]
I like the rename idea.
