### ISSUE TITLE
BUG: DMSP SSUSI SDR-Disk change in name format 

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatNASA#239]
# Description
In 2024 the SPDF database started storing DMSP SSUSI SDR-Disk data using revision numbers that are 6 numbers long instead of 5 numbers long.

Name examples:
```
dmspf18_ssusi_sdr-disk_2023010T004046-2023010T022237-REV68229_vA8.2.0r000.nc
dmspf18_ssusi_sdr-disk_2024007T003317-2024007T021508-REV073345_vA8.2.0r000.nc
```

# To Reproduce this bug:
1. Go to: https://spdf.gsfc.nasa.gov/pub/data/dmsp/dmspf18/ssusi/data/sdr-disk/2024/
2. Click on one of the doy directories
3. See files
4. Go to: https://cdaweb.gsfc.nasa.gov/
5. Click through to the CDAWeb file viewer, which will not find these files

# Additional context
We may be able to get around this issue by allowing both file formats.

**Comment by jklenzing** [comment]
Interesting. Starting on 2023, day 79, it looks like the code was updated. Duplicate files for the last file of the day. Also, day 80 has duplicate naming conventions for the whole day, and day 81 is fully switched to the 6-digit version.

https://spdf.gsfc.nasa.gov/pub/data/dmsp/dmspf18/ssusi/data/sdr-disk/2023/079/
https://spdf.gsfc.nasa.gov/pub/data/dmsp/dmspf18/ssusi/data/sdr-disk/2023/080/
https://spdf.gsfc.nasa.gov/pub/data/dmsp/dmspf18/ssusi/data/sdr-disk/2023/081/

**Comment by aburrell** [comment]
Checked and this holds true across other SSUSI instruments.
