### ISSUE TITLE
TST: specialized OMNI HRO routines need testing

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#34]
- [x] `time_shift_to_magnetic_poles`
- [x] `calculate_imf_steadiness` (w/ custom `max_wnum`)
- [x] Custom warning in `calculate_imf_steadiness`
- [x] `calculate_dayside_reconnection`
- [x] `calculate_clock_angle`

**Comment by jklenzing** [comment]
Need to evaluate the usage of these routines before writing tests

**Comment by jklenzing** [comment]
Notes on usage of `calculate_imf_steadiness`.  In pysatNASA 0.0.2, this will autofill a sample rate of 1 if a tag of '' is attached to the instrument.  This allows the routine to be run on simulated data attached to a `pysat_testing` object.  The usage of this should be evaluated in the tests.

**Comment by jklenzing** [comment]
@aburrell, do we want to maintain support for older scipy?
https://github.com/pysat/pysatNASA/blob/d5cf79a27ccc73dd9e08ce15e98d240f949ef1f5/pysatNASA/instruments/methods/omni.py#L140-L150

scipy 1.4 was released in 2019. I think we could add a limit and drop this. Not sure how we would test for this otherwise

**Comment by jklenzing** [comment]
Also, I don't see how to trigger the following lines without also creating a valueError later on due to non-integer windows. Is this the intended behaviour?
https://github.com/pysat/pysatNASA/blob/d5cf79a27ccc73dd9e08ce15e98d240f949ef1f5/pysatNASA/instruments/methods/omni.py#L114-L120

**Comment by aburrell** [comment]
I think dropping the older scipy is fine.  Maybe change lines 114-120 to just raise an earlier ValueError, or adjust the input to prevent the ValueError from happening.

**Comment by jklenzing** [comment]
The valueError comes directly from pandas when the rolling routines are invoked

**Comment by jklenzing** [comment]
Turns out it was a bug! 🐞
