### ISSUE TITLE
BUG: time zones resulting in cdf data offset by 5 hours

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#35]
Loading data from cdf objects results in a five hour time shift.  Example:
```
import pysat
plp = pysat.Instrument('cnofs', 'plp')
plp.load(2009, 1)
plp.data
```
yields
```
                                         Ni      Ni_std          dN_N  ...        SLT  Ni_quality_flag  Te_quality_flag
2009-01-01 05:00:00.000000000           NaN         NaN           NaN  ...  19.411001              NaN              NaN
2009-01-01 05:00:01.000000000           NaN         NaN           NaN  ...  19.414862              NaN              NaN
2009-01-01 05:00:02.000000000           NaN         NaN           NaN  ...  19.418720              NaN              NaN
2009-01-01 05:00:03.000000000           NaN         NaN           NaN  ...  19.422581              NaN              NaN
2009-01-01 05:00:04.000000000           NaN         NaN           NaN  ...  19.426441              NaN              NaN
...                                     ...         ...           ...  ...        ...              ...              ...
2009-01-02 04:59:55.000000000  27315.011719  338.291016  1.235920e-02  ...  15.490463              NaN              NaN
2009-01-02 04:59:55.999000072  27170.177734  215.423935  7.510136e-03  ...  15.494303              NaN              NaN
2009-01-02 04:59:57.000000000  27129.634766  169.063416  6.166598e-03  ...  15.498141              NaN              NaN
2009-01-02 04:59:58.000000000  27073.656250  126.887657  4.678100e-03  ...  15.501980              NaN              NaN
2009-01-02 04:59:58.999000072  26939.554688    0.555127  8.636658e-07  ...  15.505817              NaN              NaN

[86400 rows x 12 columns]
```
The data should run from midnight to midnight.  Opening files separately confirms that five hours are added to each data point.

**Comment by JonathonMSmith** [comment]
Just a small update here. I get this offset when I:
load plp data using cdflib (no pysatNASA)
convert the epoch data to datetime using pandas.

the cdaweb code here in pysatNASA checks for information in the cdf file that contains info about any offset. If it doesnt find any it just converts the epoch data to datetime and calls it a day.

Looking at what variables and meta data cdflib gets for cnfos plp I don't see anything indicating an offset, but I'm probably no the most familiar. Here's the output of the cdf_info() function https://github.com/MAVENSDC/cdflib#cdf_info

`{'CDF': PosixPath('/home/jon/data/cnofs/plp/cnofs_plp_plasma_1sec_20090101_v01.cdf'),
 'Version': '3.2.4',
 'Encoding': 1,
 'Majority': 'Row_major',
 'rVariables': [],
 'zVariables': ['EPOCH',
  'Ni',
  'Ni_std',
  'dN_N',
  'N_electron',
  'Te',
  'SC_POT',
  'GLAT',
  'GLON',
  'ALT',
  'SLT',
  'Ni_quality_flag',
  'Te_quality_flag'],
 'Attributes': [{'TITLE': 'Global'},
  {'Project': 'Global'},
  {'Source_name': 'Global'},
  {'Discipline': 'Global'},
  {'Data_type': 'Global'},
  {'Descriptor': 'Global'},
  {'Data_version': 'Global'},
  {'Software_version': 'Global'},
  {'PI_name': 'Global'},
  {'PI_affiliation': 'Global'},
  {'TEXT': 'Global'},
  {'Instrument_type': 'Global'},
  {'Mission_group': 'Global'},
  {'Logical_source': 'Global'},
  {'Logical_file_id': 'Global'},
  {'Logical_source_description': 'Global'},
  {'Time_resolution': 'Global'},
  {'Rules_of_use': 'Global'},
  {'Generated_by': 'Global'},
  {'Generation_date': 'Global'},
  {'Acknowledgement': 'Global'},
  {'MODS': 'Global'},
  {'ADID_ref': 'Global'},
  {'LINK_TEXT': 'Global'},
  {'LINK_TITLE': 'Global'},
  {'HTTP_LINK': 'Global'},
  {'CATDESC': 'Variable'},
  {'VAR_NOTES': 'Variable'},
  {'DEPEND_0': 'Variable'},
  {'DISPLAY_TYPE': 'Variable'},
  {'FIELDNAM': 'Variable'},
  {'FORMAT': 'Variable'},
  {'FILLVAL': 'Variable'},
  {'LABLAXIS': 'Variable'},
  {'MONOTON': 'Variable'},
  {'SCALETYP': 'Variable'},
  {'UNITS': 'Variable'},
  {'VALIDMIN': 'Variable'},
  {'VALIDMAX': 'Variable'},
  {'VAR_TYPE': 'Variable'}],
 'Copyright': '\nCommon Data Format (CDF)\n(C) Copyright 1990-2008 NASA/GSFC\nSpace Physics Data Facility\nNASA/Goddard Space Flight Center\nGreenbelt, Maryland 20771 USA\n(Internet -- CDFSUPPORT@LISTSERV.GSFC.NASA.GOV)\n',
 'Checksum': False,
 'Num_rdim': 0,
 'rDim_sizes': [],
 'Compressed': False,
 'LeapSecondUpdated': -1}`

**Comment by jklenzing** [comment]
Exploring `cdflib`, it looks like there is a routine already to handle this.
```
fname = 'cnofs_plp_plasma_1sec_20090101_v01.cdf'
cfile = cdflib.CDF(fname)
epoch = cfile.varget(variable='EPOCH')
pds.Index(cdflib.cdfepoch.to_datetime(epoch))
```
yields
```
DatetimeIndex([       '2009-01-01 00:00:00',        '2009-01-01 00:00:01',
                      '2009-01-01 00:00:02',        '2009-01-01 00:00:03',
                      '2009-01-01 00:00:04',        '2009-01-01 00:00:05',
               '2009-01-01 00:00:05.999000',        '2009-01-01 00:00:07',
                      '2009-01-01 00:00:08',        '2009-01-01 00:00:09',
               ...
                      '2009-01-01 23:59:50', '2009-01-01 23:59:50.999000',
                      '2009-01-01 23:59:52',        '2009-01-01 23:59:53',
                      '2009-01-01 23:59:54',        '2009-01-01 23:59:55',
               '2009-01-01 23:59:55.999000',        '2009-01-01 23:59:57',
                      '2009-01-01 23:59:58', '2009-01-01 23:59:58.999000'],
              dtype='datetime64[ns]', length=86400, freq=None)
```

**Comment by jklenzing** [comment]
I suspect the issue is with the pandas/datetime interaction.  I ran into this when trying to convert the timestamps for the icon instruments.  We wound up including a preprocess routine that points to `pysat.instruments.methods.general.convert_timestamp_to_datetime` which forces datetime to recognize this as a UTC timestamp.  I think the built-in routines in cdflib should streamline the process, assuming they work the way I think.

**Comment by jklenzing** [comment]
Quick fix: Replace the following lines 
https://github.com/pysat/pysatNASA/blob/8af36b664cc3ec9e72a705408d5fbceec64b3c79/pysatNASA/instruments/methods/cdaweb.py#L228-L231
with
```
xdata = cdflib.cdfepoch.to_datetime(xdata)
```
Just verified that the load routine described above now loads from midnight to midnight.  Now we just need to find a way to make this compliant with the `delta_time`, or if we need to maintain that capability.

**Comment by JonathonMSmith** [comment]
Im gonna start testing this. Hopefully this will work out great and coincide with a transition to xarray anyway.

**Comment by jklenzing** [comment]
Closing with merge of #40
