### ISSUE TITLE
BUG: ICON constellation

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#49]
The ICON constellation object still uses old tags and inst_ids, which means it will fail on load.  The new standards for these instruments will include 8-12 distinct data products, depending on completeness.  Do we want to support this in the future?

- ivm (1)
- euv (1)
- fuv(2, day and night)
- mighti vector winds (2, red and green)
- mighti temperature (2, a and b)
- mighti los winds (4, red and green, a and b)

**Comment by aburrell** [comment]
It seems like a good idea?  I like the idea of having all instruments on each of the satellite platforms load as a constellation.  However, I haven't ever used this.

**Comment by jklenzing** [comment]
Update: version for pysat 2.3.0 will leave out the los (line-of-sight) winds, since there are mapped into the the vector wind data products.

**Comment by jklenzing** [comment]
Will test modified code tonight.

**Comment by jklenzing** [comment]
Updated code works as expected
