### ISSUE TITLE
STY: cdflib and cdaweb

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#53]
Technically, cdf and CDAWeb interactions are separate entities.  CDAWeb hosts netCDF4 files as well.  We could break these into two separate method files, which would aid in finding stuff we need.  Potentially, cdflib routines could be moved to `pysatNASA.utils`, mirroring the structure in the core code.

**Comment by aburrell** [comment]
> Potentially, cdflib routines could be moved to pysatNASA.utils, mirroring the structure in the core code.

I think that's a good idea.

**Comment by jklenzing** [comment]
Closing with merge of #58
