### ISSUE TITLE
DOC: Making files for archive at NASA

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatNASA#6]
**Is your feature request related to a problem? Please describe.**
pysat can make standards compliant files for NASA archive but there is no current example on how to pull a few features together in pysat to make it happen with the least amount of hassle required on the developer. 

**Describe the solution you'd like**
Add a section, or a demo code area, that shows how file standards are maintained and enabled for the NASA ICON project.

**Describe alternatives you've considered**
Say nothing?

**Additional context**

**Comment by jklenzing** [comment]
Can use https://github.com/jklenzing/ops_reach as an example of how to set this up.

**Comment by jklenzing** [comment]
- [ ] https://github.com/jklenzing/ops_reach/pull/17
- [ ] Write tutorial based on ops_reach code

**Comment by jklenzing** [comment]
Revisiting this issue, there's nothing specific to pysatNASA we currently use for archival. Perhaps a short article in the docs pointing to the online packages used for archival?
