### ISSUE TITLE
BUG: Mapped ICON IVM ion drifts (equator, footpoints) are not cleaned

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatNASA#78]
**Describe the bug**
Ion drifts at the spacecraft are filtered from instrument flags. The ion drift values obtained by mapping spacecraft ion drifts to the footpoint, and the equator, are not included in the cleaning.

**To Reproduce**
1. Load clean data
2. Compare ion drifts at spacecraft to any mapped location, like 'Equator_Ion_Velocity_Meridional'
3. Equator values aren't filtered

**Expected behavior**
Cleaned drifts for all variables

**Desktop (please complete the following information):**
 - OS:MacOS 10.15.4
 - Version Python 3.7

**Additional context**

**Comment by jklenzing** [comment]
Closing with merge of #80
