### ISSUE TITLE
BUG: ICON IVM remote data access has changed

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#8]
IVM files are currently being stored as zip files on the ftp server.  The current code breaks when you attempt to download a file.
Options
- Add a routine to unzip the file after download, similar to cosmic_gps data
- Wait until data is migrated to CDAWeb

**Comment by jklenzing** [comment]
From running tests locally, this currently only affects ICON IVM files.

**Comment by rstoneback** [comment]
Huh. I wonder why.

They weren’t originally .zip files. The netCDF files themselves are also compressed. 

Thanks for noticing.

**Comment by aburrell** [comment]
> The netCDF files themselves are also compressed.

I wonder how much space they've saved versus how much time it took to compress them.

I guess it wouldn't hurt to put in a zip file check.  If it's done after the normal file failure, then it won't add to the download time.

**Comment by jklenzing** [comment]
Closing with merge of #16.
