### ISSUE TITLE
ICON IVM files

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatNASA#86]
**Describe the bug**
There is a duplicate time entry in the ICON IVM A files at 2020-09-22 23:59:57.776.

**To Reproduce**

```
import pysat
import datetime as dt
stime = dt.datetime(2020, 9, 22)
icon = pysat.Instrument('icon', 'ivm', inst_id='a')
icon.load(date=stime)

ValueError:  Loaded data is not unique. To continue to use data,set inst.strict_time_flag=False before loading data
```

**Expected behavior**
Using the strict time flag should not throw an error.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Version: Python 3.9
 - Other details about your setup that could be relevant: using `add_io_utils` branch in pysat.

**Comment by jklenzing** [comment]
What is the version / rev number of your data?  Loading this day with v05r000 and v05r001, I'm not duplicating the issue.

**Comment by jklenzing** [comment]
@aburrell, do you still see this issue?  IVM files are up to version 6.  Let me know if I can close this.

**Comment by aburrell** [comment]
Looks like the current version of the files has fixed this problem.
