### ISSUE TITLE
ENH: Filter ICON data so single day of data is loaded.

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatNASA#87]
**Is your feature request related to a problem? Please describe.**
As reported in https://github.com/pysat/pysatModels/pull/93 ICON data files can have data outside the listed date. Reason is 4 second chunking of satellite ephemeris. See comment https://github.com/pysat/pysatModels/pull/93#issuecomment-921078547

**Describe the solution you'd like**
We can set `multi_file_day=True` in the ICON instrument support files which will cause pysat to load data for dates +/- 1 and filter out data outside the desired date.

**Describe alternatives you've considered**
Leave as is. Can confuse users.

**Additional context**

**Comment by jklenzing** [comment]
A quick test shows that using `multi_file_day=True` works as expected above for ivm.  Load time goes from 1.65s to 4.75s (as expected).

I don't see this issue in randomly loaded dates for other data products.  I did notice that `multi_file_day` does not work for xarray instruments, so that's a new issue for pysat.  Have you seen this problem in the other instruments?

**Comment by rstoneback** [comment]
I think IVM is the only instrument that reports faster than the ephemeris. Not just ephemeris, also related to how instrument packets are grouped. EUV and FUV is every ~12s and MIGHTI is 30s.

**Comment by jklenzing** [comment]
Is this something we can make optional?  Or does `multi_file_day` have to be hardwired?

Thinking about potential problems in the future, if we effectively triple the run time for loading data when iterating over the full data set.

**Comment by rstoneback** [comment]
> 
>  I did notice that `multi_file_day` does not work for xarray instruments, so that's a new issue for pysat. 

I figured we would have a bug in that area, https://github.com/pysat/pysat/issues/266


> A quick test shows that using multi_file_day=True works as expected above for ivm. Load time goes from 1.65s to 4.75s (as expected).

It is true load times are higher. That extra cost is paid the first time data is loaded, but it is minimized for neighboring days via the cache. So if someone is iterating through the data the time cost is minimized.

Your load times are also quicker than mine :) This is with `multi_file_day` set to True.

```
In [4]: %time ivm.load(2020, 1)                                                                                                                                              
pysat INFO: Initializing three day/file window
pysat INFO: Returning icon ivm a data for 31 December 2019
pysat INFO: Returning icon ivm a data for 01 January 2020
pysat INFO: Returning icon ivm a data for 02 January 2020
CPU times: user 11.6 s, sys: 337 ms, total: 12 s
Wall time: 12.1 s

In [5]: %time ivm.load(2020, 2)                                                                                                                                              
pysat INFO: Returning icon ivm a data for 03 January 2020
CPU times: user 9.52 s, sys: 169 ms, total: 9.69 s
Wall time: 9.71 s

In [6]: %time ivm.load(2020, 3)                                                                                                                                              
pysat INFO: Returning icon ivm a data for 04 January 2020
CPU times: user 10.1 s, sys: 310 ms, total: 10.4 s
Wall time: 10.8 s

In [7]: %time ivm.load(2020, 4)                                                                                                                                              
pysat INFO: Returning icon ivm a data for 05 January 2020
CPU times: user 9.99 s, sys: 205 ms, total: 10.2 s
Wall time: 10.5 s

In [8]: %time ivm.load(2020, 5)                                                                                                                                              
pysat INFO: Returning icon ivm a data for 06 January 2020
CPU times: user 9.37 s, sys: 175 ms, total: 9.55 s
Wall time: 9.63 s

In [9]: %time ivm.load(2020, 15)                                                                                                                                             
pysat INFO: Returning icon ivm a data for 14 January 2020
pysat INFO: Returning icon ivm a data for 15 January 2020
pysat INFO: Returning icon ivm a data for 16 January 2020
CPU times: user 11.4 s, sys: 279 ms, total: 11.6 s
Wall time: 12 s
```

**Comment by rstoneback** [comment]
> Is this something we can make optional? Or does `multi_file_day` have to be hardwired?
> 

I think we used to have that option at the Instrument level but it isn't there now. Could be changed back to accept info at instantiation.

> Thinking about potential problems in the future, if we effectively triple the run time for loading data when iterating over the full data set.

See note above that loading time is not tripled when iterating.

**Comment by jklenzing** [comment]
I've got a branch ready to go.  If time is really minimized for iteration, then maybe we don't need to worry about optimization.

**Comment by rstoneback** [comment]
Load time issue was on my end, and my python environment that is setup to still be able to run pysatSeasons...

```
In [5]: %time ivm.load(2020, 1)
pysat INFO: Initializing three day/file window
pysat INFO: Returning icon ivm a data for 31 December 2019
pysat INFO: Returning icon ivm a data for 01 January 2020
pysat INFO: Returning icon ivm a data for 02 January 2020
CPU times: user 2.63 s, sys: 236 ms, total: 2.87 s
Wall time: 2.87 s

In [6]: %time ivm.load(2020, 2)
pysat INFO: Returning icon ivm a data for 03 January 2020
CPU times: user 1.01 s, sys: 133 ms, total: 1.14 s
Wall time: 1.14 s

In [7]: %time ivm.load(2020, 3)
pysat INFO: Returning icon ivm a data for 04 January 2020
CPU times: user 1.47 s, sys: 226 ms, total: 1.69 s
Wall time: 1.69 s

In [8]: %time ivm.load(2020, 4)
pysat INFO: Returning icon ivm a data for 05 January 2020
CPU times: user 1.47 s, sys: 247 ms, total: 1.71 s
Wall time: 1.71 s

In [9]: %time ivm.load(2020, 5)
pysat INFO: Returning icon ivm a data for 06 January 2020
CPU times: user 1.01 s, sys: 142 ms, total: 1.16 s
Wall time: 1.16 s

In [10]: import sys

In [11]: sys.version_info
Out[11]: sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

# Load an isolated day
In [12]: %time ivm.load(2020, 15)
pysat INFO: Returning icon ivm a data for 14 January 2020
pysat INFO: Returning icon ivm a data for 15 January 2020
pysat INFO: Returning icon ivm a data for 16 January 2020
CPU times: user 2.55 s, sys: 160 ms, total: 2.71 s
Wall time: 2.71 s
```

**Comment by rstoneback** [comment]
> I've got a branch ready to go. If time is really minimized for iteration, then maybe we don't need to worry about optimization.

optimization built-in :)

**Comment by jklenzing** [comment]
Closing with merge of #88
