### ISSUE TITLE
ENH: xarray support in CDF interface

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatNASA#92]
**Is your feature request related to a problem? Please describe.**
Currently, only pandas objects are supported. 

**Describe the solution you'd like**
xarray support needs to be added to the CDF interface to better support data products.

**Describe alternatives you've considered**
😿 

**Additional context**
precursor to #14

**Comment by jklenzing** [comment]
cdflib 0.4 includes xarray support.  Need to test this.

**Comment by JonathonMSmith** [comment]
I'd like to work on this but I need some guidance on how we want this to look.
Currently, some instruments hard code the "pandas_format" variable that specifies that they always use xarray for the data.
Is "pandas_format" something we want to be a kwarg when you instantiate a new instrument object?
Will pysatCDF get xarray support in the near future?

another thought...
If pysat were to use xarray completely, could the xarray attrs and varibale attrs completely replace the meta object?

**Comment by jklenzing** [comment]
My thought is that the cdf functions would look similar to the `load_netcdf` function in the core package.  It would accept the `pandas_format` kwarg, which stems from info hard-wired in each instrument depending on dimensionality.  Depending on the kwarg, the load statement decides whether to use existing code (pandas) or the to-be-added xarray code.  Note that if `pandas_format` is not specified in an instrument, it is assumed to be True upon instantiation by the core code.

We've talked about potentially allowing a user to load a pandas set as an xarray set with optional kwargs.  Not sure if this is on the roadmap or just a possibility.

I don't think we want to migrate completely to xarray just yet.  I've thought about this, but I think this is well out in the future if we decide to go that route.

**Comment by rstoneback** [comment]
As @jklenzing noted there is keyword argument support in load_netcdf. `pysat_netcdf` general instrument also has pandas_format keyword, which is passed to load_netcdf, to support loading into pandas or xarray.

I'd like to add xarray in the near future but I need to generate more funding so I need to hold off on doing it ahead of time. Current thinking is to apply to the new tools version of HDEE, with open submission deadlines, to add xarray support to pysatCDF. As you know, that all takes time. Was thinking of introducing this at next pysat meeting but topic came up :)

**Comment by jklenzing** [comment]
Closing with merge of #120
